  version:           2
version:              2
jobs:
  test:
    docker:
      - image:        circleci/node:9.11.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
      - run:
          name:       Setup Dependencies
          command:    npm install
      - save_cache:   # special step to save the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:          # run lint verification
          name:       Lint code
          command:    npm run lint
      - run:          #run tests
          name:       Test code
          command:    npm run test
  build:
    docker:
      - image:     circleci/node:9
      - image:        circleci/node:9.11.1
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
      - run:
          name:       Setup Dependencies
          command:    npm install
      - save_cache:   # special step to save the dependency cache
          key:        dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Lint code
          command: npm run lint
      - run: #run test
          name: Test code
          command: npm run test
      - run: #run build
          name: Build code
          command: npm run build
      - run:          # run lint verification
          name:       Lint code
          command:    npm run lint
      - run:          #run build
          name:       Build code
          command:    npm run build

workflows:
  version:            2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only:   master
