// ActionTypes are defined in constants.

// They are imported in Actions and Reducers.
// This prevents errors if they are misspelled over here.

/* eslint-disable */

export const FETCH_INFORMATION = "FETCH_INFORMATION";
export const FETCH_INFORMATION_FULFILLED = "FETCH_INFORMATION_FULFILLED";
export const FETCH_INFORMATION_REJECTED = "FETCH_INFORMATION_REJECTED";
export const POST_CONNECT = "POST_CONNECT";
export const POST_CONNECT_FULFILLED = "POST_CONNECT_FULFILLED";
export const POST_CONNECT_REJECTED = "POST_CONNECT_REJECTED";

export const LOGIN = "LOGIN";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

export const REGISTER = "REGISTER";
export const REGISTER_FULFILLED = "REGISTER_FULFILLED";
export const REGISTER_REJECTED = "REGISTER_REJECTED";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_FULFILLED = "FORGOT_PASSWORD_FULFILLED";
export const FORGOT_PASSWORD_REJECTED = "FORGOT_PASSWORD_REJECTED";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_FULFILLED = "RESET_PASSWORD_FULFILLED";
export const RESET_PASSWORD_REJECTED = "RESET_PASSWORD_REJECTED";

export const PROMOTIONS = "PROMOTIONS";
export const PROMOTIONS_FULFILLED = "PROMOTIONS_FULFILLED";
export const PROMOTIONS_REJECTED = "PROMOTIONS_REJECTED";
export const PROMOTIONS_LOAD_MORE = "PROMOTIONS_LOAD_MORE";

export const PARTNER_PAGE = "PARTNER_PAGE";
export const PARTNER_PAGE_FULFILLED = "PARTNER_PAGE_FULFILLED";
export const PARTNER_PAGE_REJECTED = "PARTNER_PAGE_REJECTED";

export const TRAFFIC = "TRAFFIC";
export const TRAFFIC_FULFILLED = "TRAFFIC_FULFILLED";
export const TRAFFIC_REJECTED = "TRAFFIC_REJECTED";

export const AFFLUENCE = "AFFLUENCE";
export const AFFLUENCE_FULFILLED = "AFFLUENCE_FULFILLED";
export const AFFLUENCE_REJECTED = "AFFLUENCE_REJECTED";

export const TYPICAL_CUSTOMER = "TYPICAL_CUSTOMER";
export const TYPICAL_CUSTOMER_FULFILLED = "TYPICAL_CUSTOMER_FULFILLED";
export const TYPICAL_CUSTOMER_REJECTED = "TYPICAL_CUSTOMER_REJECTED";

/* eslint-enable */
